
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


cloud_name=dkueai729
api_key=723635153566573
api_secret=Zz-zpigA82lEY18EZp0kEvqNLM8



