
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template


cloud_name=diqqsuiv5
api_key=762421699452284
api_secret=_1_n2rN-5OAuIH1y7KDRQs9cTEU



